@startuml Caso-04-Clases
title Consulta Rápida de Saldo

skinparam class {
  BackgroundColor White
  BorderColor Black
  ArrowColor #444444
  FontName Helvetica
}
skinparam classFontStyle bold
skinparam stereotypeCBackgroundColor #DDDDDD

class Usuario {
  -id_usuario : int
  -nombre : String
  -contraseña : String
  +autenticar() 
}

class Dueña {
  +consultarSaldo() 
}

class Ayudante {
  +consultarSaldo() 
}

class Cliente {
  -id_cliente : int
  -nombre : String
  -saldo_deudor : double
  -limite_credito: double
}

class BusquedaCliente  {
  -filtro : String
  -resultados 
  +filtrar() 
  +mostrarSinCoincidencias()
}

Usuario        <|-- Dueña
Usuario        <|-- Ayudante
Usuario        "1" --> "0..*" BusquedaCliente : ejecuta 
BusquedaCliente "1" --> "0..*" Cliente        : filtra 


@enduml