@startuml Diagrama Estado Cliente

skinparam state {
  BackgroundColor #F5EEF8
  StartColor Purple
  EndColor Indigo
  BorderColor MediumPurple
}

title Estados de un Cliente

[*] --> SinDeuda : crear()

SinDeuda : - saldo_deudor = 0
SinDeuda : - limite_credito definido
SinDeuda : ==
SinDeuda : incrementarSaldo(monto) [monto > limite] / rechazar

SinDeuda --> ConDeuda : incrementarSaldo(monto)\n[monto <= limite]\n/ sumarSaldo

ConDeuda : - saldo_deudor > 0
ConDeuda : ==
ConDeuda : incrementarSaldo(monto) [saldo + monto <= limite] / sumarSaldo
ConDeuda : incrementarSaldo(monto) [saldo + monto > limite] / rechazar

state EvaluarAbono <<choice>>

ConDeuda --> EvaluarAbono : decrementarSaldo(monto)

EvaluarAbono --> ConDeuda : [monto < saldo_deudor] / restarSaldo
EvaluarAbono --> ConDeuda : [monto > saldo_deudor] / rechazar
EvaluarAbono --> SinDeuda : [monto == saldo_deudor] / saldo_deudor = 0

note right of ConDeuda
  Las validaciones para 
  incrementar o rechazar 
  nuevas deudas ocurren
  internamente sin cambiar 
  de estado.
end note

@enduml